name: Build Linux

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build clang cmake pkg-config libgtk-3-dev liblzma-dev

      - name: Run tests
        run: |
          cd src
          pytest

      - name: Build executable
        run: |
          cd src
          flet build linux --module-name app.py --project app

      - name: Rename build directory
        run: |
          mv src/build/linux src/build/nano-fertilizers-mixer-utility

      - name: Archive build artifact
        run: |
          cd src/build
          zip -r ../../build-linux.zip nano-fertilizers-mixer-utility
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build-linux.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build-linux.zip
          asset_name: build-linux.zip
          asset_content_type: application/zip